### ISSUE TITLE
stader-cli wallet test-recovery does not exist

### ISSUE THREAD

**Issue by jbroudou** [stader-labs/stader-node#100]
Issuing `stader-cli wallet r` returns a message stating that if you want to test recovery, you should issue the statement `stader-cli wallet test-recovery` instead. This command does not work.

**Comment by bharath-123** [comment]
thanks for highlighting it, we are not planning to support this and will fix it in the next version

**Comment by bharath-123** [comment]
we have resolved this in our latest releases
