### ISSUE TITLE
This key is already in use by validator  on the Beacon chain!  - could not make validator deposit: **** ALERT ****

### ISSUE THREAD

**Issue by victorelec14** [stader-labs/stader-node#192]
Hello, 

I'm a Rocketpool validator and I wanted to create 1 node in Stader. I used the same wallet (importing the 24 words) and everything was going fine when creating the node, interacting with the contract, and depositing the collateral and Eth. The problem is that when trying to create the 2 validators, I get this error and it gives me the Rocketpool validator pubkey.

> docker exec stader_api /go/bin/stader --ignore-sync-check  --maxFee 32.000000 --maxPrioFee 2.000000 --gasLimit 100000   api validator deposit 4000000000000000000 1 true
API Out:

```
could not make validator deposit: **** ALERT ****
Your validator vicxxxxx has the following as a validator pubkey:
        b9ab3c4eb08bea2eb37417072af40777eb033068a665f0059f03f8d6a7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
This key is already in use by validator 63xxx on the Beacon chain!
Stader will not allow you to deposit this validator for your own safety so you do not get slashed.
PLEASE REPORT THIS TO THE STADER DEVELOPERS.
***************
```

Is it possible to use the same wallet? Or should I generate a new pubkey?

What happens now with the collateral I sent to the contract? Does it remain locked? or i should use the "withdraw-sd-collateral" ?

Does it have something to do with Stader trying to use the first 2 Keys/Mnemonics that are already in use by Rocketpool? The pubkey it gives me is one of them. Is it possible to make Stader generate or use a 3rd key?"

![image](https://github.com/stader-labs/stader-node/assets/543450/d63a13c1-e043-4694-997b-07f613c142ce)
https://ethereum.org/developers/docs/consensus-mechanisms/pos/keys#withdrawal-key

Thanks

**Comment by victorelec14** [comment]
I solved this part of the problem by specifying in the wallet which is the next account to use.

> "next_account":10

With that, I was able to generate the 2 new keys for the Stader validators. However, the problem now is that during installation, my Prysm node has the old encrypted wallet in the folder, which causes DoppelGanger errors and stops the node.

I've tried deleting the wallet from the validator, but upon restarting the services, the node doesn't regenerate these keys.

Is there a way to force the regeneration or importation of the wallet in the validator?

I've seen that it's possible to tell the validator which keys to use; perhaps the node can be improved by adding this feature to use only the keys from Stader and not from Rocketpool, or by selecting which keys to use in the panel.

https://github.com/prysmaticlabs/prysm/issues/7485

Thank you.

**Comment by batphonghan** [comment]
Hi there, thank you for brings this. We're not recommend to use same node for both rocket pool and stader.
For now, you can recover your stader-node validator keys + wallet key by:
1. Remove your data: `rm -rf ~/.stader/data`
2. Recover wallet + validator keys 
```
stader-cli wallet r -m 'your_mnonomic' --password 'some_password'
```

**Comment by victorelec14** [comment]
Hi @batphonghan ,

At the beginning, I used the wallet recover command to import the wallet I was using with Rocketpool. However, the importer doesn't know which wallet is next or which ones are already in use ( "next_account" ). It also doesn't differentiate between keys created by Stader and those by Rocketpool.

With the doppelganger error, I managed to solve it by running the validator separately and deleting the first imported key (Rocketpool). Now only the 2 from Stader remain, and the node no longer restarts. However, this is only a fix for Prysm (/validators/prysm-non-hd/direct/accounts/all-accounts.keystore.json) because the other key is still in the wallet file. Therefore, when updating or regenerating the keys, they will return.

It would be good to create an option that allows you to select which keys you want to use in the node. This is also important in case you have a node with a Stader wallet with 2 keys and you want to use that same wallet to move only one key to another hardware/validator.

For example:
```
Node1 > Wallet 1 -> validator1, validator2
```
to
```
Node 1 > Wallet1-> validator1
Node 2 > Wallet1 -> validator2
```

I also saw that when switching to Lighthouse, files are generated with each wallet in a separate file. There, it's much easier to delete the key you don't need in this node. 

![image](https://github.com/stader-labs/stader-node/assets/543450/9f01eda3-6b3a-4458-ac25-0482d3319be4)

In case anyone has the same problem with Prysm as me, I'll leave the steps to delete the keys you don't want to use.

Run this and choose which keys you want to delete.

List Keys:
```shell
docker run -it -v $HOME/.stader/data/validators:/validators gcr.io/prysmaticlabs/prysm/validator:v4.2.1 accounts list --accept-terms-of-use --wallet-dir /validators/prysm-non-hd --wallet-password-file /validators/prysm-non-hd/direct/accounts/secret 
```

Delete keys:
```shell
docker run -it -v $HOME/.stader/data/validators:/validators gcr.io/prysmaticlabs/prysm/validator:v4.2.1 accounts delete --accept-terms-of-use --wallet-dir /validators/prysm-non-hd --wallet-password-file /validators/prysm-non-hd/direct/accounts/secret 
```

Thanks

**Comment by batphonghan** [comment]
Hi there. Our recover process only check with stader contract register to see if any validator keys need to recover. If you really need to use the same node wallet (we're not recommend), I think you can manual edit `next_acount` to sum of all validator keys been derived from this wallet.
