### ISSUE TITLE
`stader-cli` lighthouse version is not Dencun ready

### ISSUE THREAD

**Issue by crypto-services** [stader-labs/stader-node#196]
`stader-cli` is currently implementing lighthouse v4.6.0 as the bn/vc client in the latest release. This version is not ready for the mainnet Dencun fork and needs to be updated to version v5.x.x as detailed here -https://github.com/sigp/lighthouse/releases/tag/v5.0.0

**Comment by batphonghan** [comment]
Hi there, we're aware of this. We're going to release new stader-node version in up coming days.
